# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np

a = np.random.randint(10, size=6)

print('list(a): ', list(a))
print('a.tolist(): ', a.tolist())

b = np.random.randint(10, size=6).reshape(3,2)

print('list(b): ', list(b))
print('b.tolist(): ', b.tolist())

list(a):  [5, 0, 1, 8, 7, 8]
a.tolist():  [5, 0, 1, 8, 7, 8]
list(b):  [array([7, 6]), array([0, 7]), array([3, 7])]
b.tolist():  [[7, 6], [0, 7], [3, 7]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件
import numpy as np

In [2]:

a = np.random.randint(10, size=6) 

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[6 2 0 4 3 8]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [3]:
b = np.random.randint(10, size=(3,4)) 

print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[2 7 3 4]
 [9 0 1 8]
 [9 2 8 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [4]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[3 0]
  [9 7]
  [7 1]]

 [[8 1]
  [4 5]
  [6 5]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [10]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))
print(type(a))


[0, 2, 1, 5, 3, 0]
[0, 2, 1, 5, 3, 0]
<class 'numpy.ndarray'>


In [6]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[9, 8, 5, 7], [9, 6, 8, 4], [3, 4, 4, 4]]
[array([9, 8, 5, 7]), array([9, 6, 8, 4]), array([3, 4, 4, 4])]


In [15]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.tolist())
print(list(c))


[[[8 6]
  [9 8]
  [2 8]]

 [[4 7]
  [5 7]
  [8 3]]]
[[[8, 6], [9, 8], [2, 8]], [[4, 7], [5, 7], [8, 3]]]
[array([[8, 6],
       [9, 8],
       [2, 8]]), array([[4, 7],
       [5, 7],
       [8, 3]])]


In [18]:
## 簡單版
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 2, 1, 5, 3, 0]
[[9, 8, 5, 7], [9, 6, 8, 4], [3, 4, 4, 4]]
[[[8, 6], [9, 8], [2, 8]], [[4, 7], [5, 7], [8, 3]]]


In [17]:
## 進階版

def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 2, 1, 5, 3, 0]
[[9, 8, 5, 7], [9, 6, 8, 4], [3, 4, 4, 4]]
[[[8, 6], [9, 8], [2, 8]], [[4, 7], [5, 7], [8, 3]]]
